name: Dependabot auto-merge

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Lint
        run: |
          rm eslint-typegen.d.ts
          pnpm run lint:fix

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action #mandatory for the output to show up in ${{ steps }}
      
      - name: Throw an error if there are changes
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: exit 1

  test:
    needs: format-code
    strategy:
      matrix:
        node: [lts/*]
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Install Global Packages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm install -g publint @arethetypeswrong/cli knip

      - name: Lint
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm run lint

      - name: Type check
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: Pub Lint
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: publint

      - name: Are The Types Wrong
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: attw --pack .

      - name: Knip
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: knip

  dependabot:
    needs: test
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
